version: '3'
services:


  prisma:
    env_file:
      - .env
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - ${PRISMA_SERVE_PORT}:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            user: root
            password: prisma
            rawAccess: true
            port: 3306
            migrations: true


  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql


  static-and-api:
    env_file:
      - .env
    image: node:12.10.0
    volumes:
      - .:/srv/online-game
    working_dir: /srv/online-game
    depends_on:
      - prisma
    ports:
      - ${DOCKER_PUBLIC_WEB_AND_API_PORT}:${PUBLIC_WEB_AND_API_PORT}
    command: npm run static-and-api-dev


volumes:
  mysql: