version: '3'


services:
  prisma:
    env_file:
      - .env
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - ${PRISMA_SERVE_PORT}:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            user: root
            password: prisma
            rawAccess: true
            port: 3306
            migrations: true


  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql


  static-and-api:
    user: ${DOCKER_USER}
    env_file:
      - .env
    image: node:${DOCKER_NODE_VERISON}
    volumes:
      - .:${DOCKER_FILE_DIRECTORY}
    working_dir: ${DOCKER_FILE_DIRECTORY}
    links:
      - prisma
    depends_on:
      - prisma
    ports:
      - ${DOCKER_PUBLIC_WEB_AND_API_PORT}:${PUBLIC_WEB_AND_API_PORT}
    expose:
      - ${DOCKER_PUBLIC_WEB_AND_API_PORT}
    command: npm run static-and-api


  games-manager:
    user: ${DOCKER_USER}
    env_file:
      - .env
    image: node:${DOCKER_NODE_VERISON}
    volumes:
      - .:${DOCKER_FILE_DIRECTORY}
    working_dir: ${DOCKER_FILE_DIRECTORY}
    links:
      - prisma
    depends_on:
      - prisma
    ports:
      - ${DOCKER_PUBLIC_GAME_WS_PORT}:${PUBLIC_GAME_WS_PORT}
      - ${DOCKER_PRIVATE_GAME_API_PORT}:${PRIVATE_GAME_API_PORT}
    expose:
      - ${DOCKER_PUBLIC_GAME_WS_PORT}
      - ${DOCKER_PRIVATE_GAME_API_PORT}
    command: npm run games-manager


  lobby-manager:
    user: ${DOCKER_USER}
    env_file:
      - .env
    image: node:${DOCKER_NODE_VERISON}
    volumes:
      - .:${DOCKER_FILE_DIRECTORY}
    working_dir: ${DOCKER_FILE_DIRECTORY}
    links:
      - prisma
    depends_on:
      - prisma
    ports:
      - ${DOCKER_PUBLIC_GLOBAL_LOBBY_WS_PORT}:${PUBLIC_GLOBAL_LOBBY_WS_PORT}
    expose:
      - ${DOCKER_PUBLIC_GLOBAL_LOBBY_WS_PORT}
    command: npm run lobby-manager


volumes:
  mysql: